# Generated by Django 4.2.4 on 2023-09-02 07:28

from django.db import migrations, models


def set_images_size(apps, _):
    Image = apps.get_model('shop', 'Image')
    for i, image in enumerate(Image.objects.all(), start=1):
        image.size = image.image.size
        image.save(update_fields=('size',))
        print(i, '[IMAGE SAVED]', image.size)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=set_images_size,
            reverse_code=migrations.RunPython.noop
        )
    ]
